// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SetZerotierNetworkStatusJSONBodyStatus.
const (
	Offline SetZerotierNetworkStatusJSONBodyStatus = "offline"
	Online  SetZerotierNetworkStatusJSONBodyStatus = "online"
)

// Valid indicates whether the value is a known member of the SetZerotierNetworkStatusJSONBodyStatus enum.
func (e SetZerotierNetworkStatusJSONBodyStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	default:
		return false
	}
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	//
	// Example:
	Message *string `json:"message,omitempty"`
}

// HealthPorts defines model for HealthPorts.
type HealthPorts struct {
	TCP *[]int `json:"tcp,omitempty"`
	UDP *[]int `json:"udp,omitempty"`
}

// HealthServices defines model for HealthServices.
type HealthServices struct {
	NotRunning *[]string `json:"not_running,omitempty"`
	Running    *[]string `json:"running,omitempty"`
}

// SuccessResponseString defines model for SuccessResponseString.
type SuccessResponseString struct {
	// Data When the interface returns success, this field is the specific success information
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	//
	// Example:
	Message *string `json:"message,omitempty"`
}

// ZTInfo defines model for ZTInfo.
type ZTInfo struct {
	// Id Example: 1234567890
	Id *string `json:"id,omitempty"`

	// Name Example: CasaOS
	Name *string `json:"name,omitempty"`

	// Status Example: online
	Status *string `json:"status,omitempty"`
}

// GetHealthPortsOK defines model for GetHealthPortsOK.
type GetHealthPortsOK struct {
	Data *HealthPorts `json:"data,omitempty"`

	// Message message returned by server side if there is any
	//
	// Example:
	Message *string `json:"message,omitempty"`
}

// GetHealthServicesOK defines model for GetHealthServicesOK.
type GetHealthServicesOK struct {
	Data *HealthServices `json:"data,omitempty"`

	// Message message returned by server side if there is any
	//
	// Example:
	Message *string `json:"message,omitempty"`
}

// GetZTInfoOK defines model for GetZTInfoOK.
type GetZTInfoOK = ZTInfo

// ResponseClientError defines model for ResponseClientError.
type ResponseClientError = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseStringOK defines model for ResponseStringOK.
type ResponseStringOK = SuccessResponseString

// CheckUploadChunkParams defines parameters for CheckUploadChunk.
type CheckUploadChunkParams struct {
	// Path File path
	Path string `form:"path" json:"path"`

	// RelativePath File path
	RelativePath string `form:"relativePath" json:"relativePath"`

	// Filename File name
	Filename string `form:"filename" json:"filename"`

	// ChunkNumber chunk number
	ChunkNumber string `form:"chunkNumber" json:"chunkNumber"`

	// TotalChunks total chunks
	TotalChunks int `form:"totalChunks" json:"totalChunks"`
}

// PostUploadFileMultipartBody defines parameters for PostUploadFile.
type PostUploadFileMultipartBody struct {
	// ChunkNumber Example: 20
	ChunkNumber *string `json:"chunkNumber,omitempty"`

	// ChunkSize Example: 1024
	ChunkSize *string `json:"chunkSize,omitempty"`

	// CurrentChunkSize Example: 1024
	CurrentChunkSize *string             `json:"currentChunkSize,omitempty"`
	File             *openapi_types.File `json:"file,omitempty"`

	// Filename Example: /DATA/test2.log
	Filename *string `json:"filename,omitempty"`

	// Identifier Example: test.log
	Identifier *string `json:"identifier,omitempty"`

	// Path Example: /DATA
	Path *string `json:"path,omitempty"`

	// RelativePath Example: /DATA/test.log
	RelativePath *string `json:"relativePath,omitempty"`

	// TotalChunks Example: 2
	TotalChunks *string `json:"totalChunks,omitempty"`

	// TotalSize Example: 1024
	TotalSize *string `json:"totalSize,omitempty"`
}

// SetZerotierNetworkStatusJSONBody defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBody struct {
	// Status Example: online
	Status *SetZerotierNetworkStatusJSONBodyStatus `json:"status,omitempty"`
}

// SetZerotierNetworkStatusJSONBodyStatus defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBodyStatus string

// PostUploadFileMultipartRequestBody defines body for PostUploadFile for multipart/form-data ContentType.
type PostUploadFileMultipartRequestBody PostUploadFileMultipartBody

// SetZerotierNetworkStatusJSONRequestBody defines body for SetZerotierNetworkStatus for application/json ContentType.
type SetZerotierNetworkStatusJSONRequestBody SetZerotierNetworkStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CheckUploadChunk Check upload chunk
	// (GET /file/upload)
	CheckUploadChunk(ctx echo.Context, params CheckUploadChunkParams) error
	// PostUploadFile Upload file
	// (POST /file/upload)
	PostUploadFile(ctx echo.Context) error
	// GetHealthlogs Get log
	// (GET /health/logs)
	GetHealthlogs(ctx echo.Context) error
	// GetHealthPorts Get port in use
	// (GET /health/ports)
	GetHealthPorts(ctx echo.Context) error
	// GetHealthServices Get service status
	// (GET /health/services)
	GetHealthServices(ctx echo.Context) error
	// GetZerotierInfo Get Zerotier info
	// (GET /zt/info)
	GetZerotierInfo(ctx echo.Context) error
	// SetZerotierNetworkStatus Set Zerotier network status
	// (PUT /zt/{network_id}/status)
	SetZerotierNetworkStatus(ctx echo.Context, networkId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CheckUploadChunk converts echo context to params.
func (w *ServerInterfaceWrapper) CheckUploadChunk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckUploadChunkParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", ctx.QueryParams(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Required query parameter "relativePath" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "relativePath", ctx.QueryParams(), &params.RelativePath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relativePath: %s", err))
	}

	// ------------- Required query parameter "filename" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "filename", ctx.QueryParams(), &params.Filename, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filename: %s", err))
	}

	// ------------- Required query parameter "chunkNumber" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "chunkNumber", ctx.QueryParams(), &params.ChunkNumber, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chunkNumber: %s", err))
	}

	// ------------- Required query parameter "totalChunks" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "totalChunks", ctx.QueryParams(), &params.TotalChunks, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter totalChunks: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CheckUploadChunk(ctx, params)
	return err
}

// PostUploadFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadFile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUploadFile(ctx)
	return err
}

// GetHealthlogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthlogs(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthlogs(ctx)
	return err
}

// GetHealthPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthPorts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthPorts(ctx)
	return err
}

// GetHealthServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthServices(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthServices(ctx)
	return err
}

// GetZerotierInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetZerotierInfo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetZerotierInfo(ctx)
	return err
}

// SetZerotierNetworkStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetZerotierNetworkStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "network_id" -------------
	var networkId string

	err = runtime.BindStyledParameterWithOptions("simple", "network_id", ctx.Param("network_id"), &networkId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter network_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetZerotierNetworkStatus(ctx, networkId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/health/services", wrapper.GetHealthServices, options.OperationMiddlewares["getHealthServices"]...)
	router.GET(options.BaseURL+"/health/ports", wrapper.GetHealthPorts, options.OperationMiddlewares["getHealthPorts"]...)
	router.GET(options.BaseURL+"/health/logs", wrapper.GetHealthlogs, options.OperationMiddlewares["getHealthlogs"]...)
	router.GET(options.BaseURL+"/file/upload", wrapper.CheckUploadChunk, options.OperationMiddlewares["checkUploadChunk"]...)
	router.POST(options.BaseURL+"/file/upload", wrapper.PostUploadFile, options.OperationMiddlewares["postUploadFile"]...)
	router.GET(options.BaseURL+"/zt/info", wrapper.GetZerotierInfo, options.OperationMiddlewares["getZerotierInfo"]...)
	router.PUT(options.BaseURL+"/zt/:network_id/status", wrapper.SetZerotierNetworkStatus, options.OperationMiddlewares["setZerotierNetworkStatus"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fhfb9s2EP8qBLeHdpCt1Gm3zm9p2qZBsSaoUwxoY7S0dLbYSKRKHpO4gb77QFKSJUt2ktYZhj0lFu/v",
	"7/7wjjc0klkuBQjUdHxDFehcCg3uxxHgG2ApJqdSoT55a79FUiAItP+yPE95xJBLEX7VUthvOkogY+40",
	"TU/mdPzphv6qYE7H9JdwpSr0dDp8wTS8L3XSIrihuZI5KOTegpihE7ZNRMNEWhTFtCiKgMagI8Vzaxsd",
	"05O3tAhW7kxAXfII/uMeVVbe6tTHs2Mxl/d0Zpt+L5Bu1Fm5d5hyEPhKKal2prsNX9cCr5N4pQ1bjgWC",
	"Eiy1qIH6d22qdBOvvGvcBBUXix1GaGKiCLRuy98UsCIopboEbDkzXk/PDLRmC3fQFlQeEAVolICYzJZE",
	"e3c1j4HwOcEEFBCuCRNLGlC4ZlmeAh1TGlAFLD4R6ZKOURkIKC5ze6IbhjfruGMXRrn9wxEy97sW/nyv",
	"FsYFwgIc8OUXphSzplwPFnIgWGa/nR2eWgoTbxD4bP+eAj+8PG06UJdtxwch8bMyQliPe1XTiGkm9VB7",
	"EbQD05odRUDvIm+wYAhXbHl3udab/hTbdRtsJ9nfCQibRsQir+YsqvJNE+3NCQgmXJM5hzS2qWaJdQ4R",
	"n/OooiFczKXKXF3RnlSbFgEtW1wnRjxuI/hktP/02e9/PP9zrw81nwFN+kOm2cmkj1YjQ7MWHylSLqDP",
	"RssAkVEclxOLqLeOOf8+o7wA1yy4BS0BFoOilTX0wGAiFf++5j/L+VsoY8tL39vovwdvvSthUqkfzLnS",
	"SCKZZUZwXBLbwLgwTjyRruxJyXhwejw8F6+uuUYuFtVXJQ0CYSImmYxNCsQaqglTLrqM225y5XqHzSOG",
	"fMZTjstzoeCb4QpclLPhuTgX7yGXCgnX2lgJIiZfJRckV/IrREhiriOjNZfCJoFlOxefareOOL4xM6Ig",
	"l5qjVMvpowQx1+MwXHBMzGwYySx8FWdGxK/NYLS/H1a8j4fnDkqOLm61yIPTYxrQS1DaQ3g5sqGWOQiW",
	"czqm+8O94T4NaM4wcREM5zyF0OSpZC7TFoDdQBwmEF2UHZVYBjJLZXRBEqbJDEAQzw8xeSQAYk1QkhlY",
	"dPmcQ0xShqAeU2eIcnE6jiuxHxzrYWLEhbNLsQwQlHYF3TbjtdVsLW818/DlwdlBiKBxmMoFDXwSfjOg",
	"lqscLLnKAMZV119dbusJH+xQuYKUIb+E090Y4aQ2jbhFvQ1YyfMTqiMbISJMNnO1XWt/0q/Ukb+rqH9C",
	"L0pkKXHidFPvqF+vIz+sqG/VW9+oxTRo7xqjvb1NQ09NF3bmqSKgT+/D2JxYi4A+uw9v34Tp+rTJMqaW",
	"dd364vQQ2p7BFra4XC5Re/XkUvfUvK9LV+2dwj2VGv35a39scQaNL2S8XBspM5Miz5nC0F6Bg+qaXQWi",
	"fd0106Z1M4167ztHPuHf1y69J3ujp73kRikQeHg/LgfB+Ib6O5yO6YwL5nKul7R7B6+axKgs0w4jj0Gg",
	"bZZrbjdKu8PjmlFXUR9pqwNtsG2TmmZFtUOykfqu2K7mPDmz92U5aPzv6rBdS2sFWAQ0TNykHqZyoRuX",
	"cLvo6tcCR9WP0oZdTkYIONCogGXt6rs1pzet3DtG6AiQlPlXouN9JRlgImPdximvdrLtQPnV7UfyqfPQ",
	"9DAe+9lREKPhjp7rxjLXO6pZseUORvyEb0diYFFCvpTb129fSClm2OnsnSepn4Ov8bD1MAiWjpSu3gbi",
	"dwyrTWMjeB9BSeSg3NLWC1BF4Ra2H4SnfiJ7GFhaTjRQqb93cLkRgFdSXXzmcRGuVsPc9MA0aWoo+coI",
	"dAGbrAB750knVay2DvuVXB5XY205fJeD3sree82X023Dyvb3r/ak0lifhcksuPXyLOdz9980uMtqvas7",
	"8GGzakvMb8mvxsuBC3P7zeDT1IbEP9z5NDAqtXPJ5Sj0/YpaglLBepKcJaChUuYWeKMhtutn5EZfu6/6",
	"zul281VDbL8RuEOmtYw4Q4irrqKHZJVvaw2lu6icJUDcflabk6byiiylsfa4ByQWIbnimLhJwD8XxFxB",
	"hFJx0ESKpl16qRGy4cqCpnAHyvUA2eJISZN7bEq6v0qSLc1wWvwTAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
